# Listen on IPv4
listen=YES
listen_ipv6=NO

# Disable anonymous login (users without accounts on the system)
anonymous_enable=NO

# Enable local users (users with accounts on the system) to log in
local_enable=YES

# Allow write operations
write_enable=YES

# Set local umask permissions for uploaded files 
# "022 means directory permissions 755 and file permissions 644"
local_umask=022

# Enable passive mode
# passive mode allows clients to establish data connections to the server,
# which is necessary for certain network configurations (e.g., behind a firewall)
pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
pasv_address=0.0.0.0

# Chroot users to their home directory
# (prevents them from navigating to other parts of the filesystem outside their home directory)
chroot_local_user=YES
# This option allows users to write files in their chrooted environment.
allow_writeable_chroot=YES

# Use local time
use_localtime=YES